---
name: Authen-Libwrap
version: 0.21
author:
  - 'James FitzGibbon, E<lt>jfitz@CPAN.orgE<gt>'
abstract: "access to Wietse Venema's TCP Wrappers library"
license: perl
requires:
  Scalar::Util: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Authen::Libwrap:
    file: lib/Authen/Libwrap.pm
    version: 0.21
resources:
  license: http://dev.perl.org/licenses/
